[package]
name = "planten_coreutils"
version = "0.1.0"
edition = "2024"

[dependencies]
nix = "0.30.1"
planten_ns = { version = "0.1.0", path = "../../libs/planten_ns" }
tempfile = "3.23.0"

[dev-dependencies]
assert_cmd = "2.1.1"
